// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Data.Concrete;

#nullable disable

namespace StoreApp.web.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20251129152720_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoreApp.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Elektronik",
                            Description = "13 inç, Intel i7, 16GB RAM, 512GB SSD",
                            Name = "Dell XPS 13 9310",
                            Price = 58000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Elektronik",
                            Description = "128GB, A17 Bionic, OLED Ekran",
                            Name = "iPhone 15 Pro",
                            Price = 80000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Aksesuar",
                            Description = "Gürültü önleyici kablosuz kulaklık",
                            Name = "Sony WH-1000XM5",
                            Price = 9000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Elektronik",
                            Description = "11 inç, 256GB, Android Tablet",
                            Name = "Samsung Galaxy Tab S9",
                            Price = 45000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Aksesuar",
                            Description = "Kablosuz mouse, ergonomik tasarım",
                            Name = "Logitech MX Master 3",
                            Price = 2500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
